# Generated by Django 3.2.9 on 2021-11-15 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_example', '0003_alter_account_las_change_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='las_change_date',
            new_name='last_change_date',
        ),
    ]
