# Generated by Django 3.2.9 on 2021-11-15 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_example', '0004_rename_las_change_date_account_last_change_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
