# Generated by Django 3.2.9 on 2021-11-21 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_example', '0005_delete_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=0, verbose_name='Age'),
        ),
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.TextField(default='Colombia', verbose_name='Location'),
        ),
    ]
